### ISSUE TITLE
HrefAsync is confusing

### ISSUE THREAD

**Issue by Meir017** [hlaueriksson/playwright-dotnet-contrib#2]
https://github.com/hlaueriksson/playwright-dotnet-contrib/blob/f5ed96003f4612c85ec61d854152a975569fc109/src/Playwright.Contrib.Extensions/ElementHandleAttributeExtensions.cs#L35-L36

there is a different when calling `a.href` and `a.getAttribute('href')`.

`a.href` returns the full URL including the domain
`a.getAttribute('href')` returns the value of the attribute which can be relative too

**Comment by hlaueriksson** [comment]
@Meir017 Thanks for spotting this!

Using `a.href` and getting the absolute URL sounds like a better implementation.

**Comment by hlaueriksson** [comment]
@Meir017 what do you think about PR #3?

**Comment by Meir017** [comment]
LGTM
